spring:
  application:
    name: article
  graphql:
    graphiql:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://localhost:27017
      database: echowire


server:
  port: 8090

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

