spring:
  application:
    name: news-ingest
  kafka:
    bootstrap-servers: localhost:9092


echowire:
  rss:
    sources: https://feeds.bbci.co.uk/news/rss.xml, https://hnrss.org/frontpage
server:
  port: 8082
#